language: scala
services:
  - mongodb
scala:
  - 2.11.1
  - 2.10.4
  - 2.9.3
jdk:
  - oraclejdk8
script:
  - sbt clean coverage test coverageReport &&
    sbt coverageAggregate
after_success:
  - sbt coveralls
